feat: auth 구현
Q-int/Qint_backend pull request #3
Opened 2024-08-09 12:47 UTC by in-jun

- feat: User엔티티 추가
- feat: RefreshToken엔티티 추가
- feat: RefreshTokenRepository추가
- chore: 의존성 추가
- feat: 토큰으로 엔티티 찾기
- feat: AuthDetails 추가
- feat: JwtProperties 추가
- feat: UserRepository 추가
- feat: 이메일로 user를 가져오는 UserFacade 추가
- feat: 이메일로 유저를 가져오는 AuthDetailsService 추가
- feat: errorCode 추가
- feat: UserNotFoundException 추가
- feat: 예외 추가
- feat: JwtTokenProvider 추가
- feat: TokenResponse
- feat: JwtFilter 추가
- feat: FilterConfig 수정
- feat: Config 추가
- fix: 코드 수정

2024-08-10 13:49 UTC, Daybreak312 requested changes

2024-08-10 13:49 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/security/jwt/JwtFilter.java
> +            Authentication authentication = jwtTokenProvider.authentication(token);
authentication은 엄연한 명사이기 때문에 동작을 설명하는 함수 네이밍엔 맞지 않다고 봅니다.
getAuthenticationFromToken 등으로 수정해주세요.

2024-08-10 13:49 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/auth/domain/RefreshToken.java
> +public class RefreshToken {
생명주기가 매우 빠른 토큰 특성상 RDB에 저장하는 건 좋지 않아보입니다.
그리고 접근주기 또한 빨라 조금 더 빠른 접근 시간이 필요합니다.
또한 토큰의 경우는 일정 시간이 지나면 무효해지기 때문에, 무효화된 데이터를 제거하는 기능이 필요합니다.

따라서 인메모리 데이터베이스이며, TimeToLive를 지원하는 NoSQL Redis에 대해 공부해보시고 적용해보시면 좋을 것 같습니다.

2024-08-10 13:49 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/security/jwt/JwtTokenProvider.java
> +                .claim("role", role)
문자열들 ACCESS_TOKEN, REFRESH_TOKEN처럼 상수화 해두는 게 보기 좋을 것 같습니다

2024-08-10 13:49 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/security/jwt/JwtTokenProvider.java
> +                && bearer.length() > jwtProperties.getPrefix().length() + 1)
조건식이 너무 기니깐 isBearerToken 등의 네이밍으로 새로운 함수 만드는 게 가독성 면에서 좋아보입니다. (함수 추출 기법)

2024-08-10 13:49 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/auth/domain/RefreshToken.java
> +    private User user;
굳이 UserJpaEntity와 연관 관계를 맺은 이유가 있을까요?
User의 email 외에 다른 데이터를 사용하지 않아서 email을 그대로 저장하는 것만으로 충분해보입니다.
지금 상태에선 불필요한 추가 SELECT 쿼리가 발생하게 됩니다.

2024-08-10 13:49 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/user/domain/User.java
> +    private Long incorrectAnswers;
전체적으로 nullable, updatable 명시해주면 좋을 것 같습니다.

2024-08-10 13:49 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/security/jwt/TokenRefreshUtil.java
> +    @Value("${auth.jwt.refreshExpiration}") private long refreshExpiration;
JwtProperties 참조하지 않고 정적으로 명시한 이유가 있을까요?

2024-08-10 13:49 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/security/jwt/TokenRefreshUtil.java
> +                .orElseThrow(() -> InvalidTokenException.EXCEPTION);
코드를 map 함수를 이용해 작성한 데에 이유가 있을까요?

콜백 함수가 꽤 긴 편이라 되려 가독성이 떨어질 수 있어보입니다.

2024-08-11 07:28 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/security/jwt/JwtFilter.java
> +            Authentication authentication = jwtTokenProvider.authentication(token);
[9367c2c](https://github.com/Q-int/Qint_backend/pull/3/commits/9367c2cf0f1537d2daca9c809117b1de7ef27ea6)

2024-08-12 10:33 UTC, in-jun commented on src/main/java/org/example/qint_backend/domain/user/domain/User.java
> +    private Long incorrectAnswers;
[81f3684](https://github.com/Q-int/Qint_backend/pull/3/commits/81f368481e9775c9051e689ae81e83660daea59d)

2024-08-12 10:42 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/security/jwt/JwtTokenProvider.java
> +                && bearer.length() > jwtProperties.getPrefix().length() + 1)
[f8f4b3a](https://github.com/Q-int/Qint_backend/pull/3/commits/f8f4b3a78a6219c759b8ec1aa2a7c94822752163)

2024-08-12 10:45 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/security/jwt/TokenRefreshUtil.java
> +    @Value("${auth.jwt.refreshExpiration}") private long refreshExpiration;
[63fc743](https://github.com/Q-int/Qint_backend/pull/3/commits/63fc7438d2641aff0b309946ed8ad8bb093c2f0d)

2024-08-12 10:57 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/security/jwt/TokenRefreshUtil.java
> +                .orElseThrow(() -> InvalidTokenException.EXCEPTION);
[40dd608](https://github.com/Q-int/Qint_backend/pull/3/commits/40dd608ce0b7a5e61b88abdca9d603a0f625cf58)

2024-08-12 11:03 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/security/jwt/JwtTokenProvider.java
> +                .claim("role", role)
[3c07f48](https://github.com/Q-int/Qint_backend/pull/3/commits/3c07f48b5122abf27a1be38360666e7b52abf55d)

2024-08-21 00:38 UTC, in-jun commented on src/main/java/org/example/qint_backend/domain/auth/domain/RefreshToken.java
> +    private User user;
[eb5b25f](https://github.com/Q-int/Qint_backend/pull/3/commits/eb5b25fff7a563e3c3c0af93d3170db2d3b3538c)
[dedd1c2](https://github.com/Q-int/Qint_backend/pull/3/commits/dedd1c21a6cfc5e86ced5d17ac0bfa084df07026)

2024-08-22 03:43 UTC, in-jun commented on src/main/java/org/example/qint_backend/domain/auth/domain/RefreshToken.java
> +public class RefreshToken {
[66835b2](https://github.com/Q-int/Qint_backend/pull/3/commits/66835b2ef3fc586f38e38b634a1c76855cd211a2)
[ad8a679](https://github.com/Q-int/Qint_backend/pull/3/commits/ad8a679d580bef96972ddbc64f0509c9720fd027)
[ad8a679](https://github.com/Q-int/Qint_backend/pull/3/commits/ad8a679d580bef96972ddbc64f0509c9720fd027)

2024-08-23 11:16 UTC, Daybreak312 requested changes
전체적으로 코드는 잘 짰습니다.
남긴 코멘트 보고 반영해주시고, 마찬가지로 왜 그래야하는지 궁금하면 질문해주세요.

2024-08-23 11:16 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/auth/service/LoginService.java
> +        return jwtTokenProvider.generateToken(user.getEmail(), "USER");
권한 정보는 Enum으로 관리하는 게 좋을 것 같아요

2024-08-23 11:16 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/err/exception/ErrorCode.java
> +    EMAIL_NOT_VERIFIED(412, "email not verified"),
상태 코드 412는 Precondition 헤더와 관련된, 요구 사항과 맞지 않는 상태 코드로 보입니다.
예외 상황을 보는 관점에 따라 400, 401 등을 내려주는 것이 좋을 것 같습니다.
클라이언트가 정상적인 흐름을 따르지 않았다고 보면 400, 인증을 하지 않았다고 보면 401처럼요.

2024-08-23 11:16 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/email/service/EmailVerifyService.java
> +public class EmailVerifyService {
이메일이 이미 사용 중인지를 확인하는 서비스로 보이나,
EmailVerify 의 뜻은 이메일 검증이기 때문에 요구 사항과 적절치 않은 이름이라고 생각합니다.

애매하긴 하지만, CheckUsedEmailService 등으로 리네임하는게 적절하다 봅니다.

2024-08-23 11:16 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/err/exception/ErrorCode.java
> +    EMAIL_VERIFICATION_NOT_FOUND(404, "email_verification not found"),
RDB에 이메일 인증 row가 없다는 것은 이메일 인증을 시도한 이력이 없음을 나타내는 에러인 것으로 보입니다.

데이터베이스에서 찾지 못한 것은 백엔드 로직에서의 예외이기 때문에 클라이언트는 이것이 무엇을 의미하는지 정확히 알 수 없습니다.
이를 클라이언트가 이해 가능하도록 적절히 변환해주어야 합니다.

401 Email Doesn't verified. 정도가 적당해보입니다.

2024-08-23 11:16 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/security/jwt/JwtProperties.java
> +    private String header;
인증 정보는 Authorization 헤더로 보내는 것이 HTTP 표준이기 때문에 저의 경우는 secret으로 돌리지 않고, 스프링에서 제공하는 HttpHeaders.AUTHORIZATION을 이용하는 편입니다.

원하는 대로 사용해주세요.

2024-08-24 03:49 UTC, in-jun commented on src/main/java/org/example/qint_backend/domain/email/service/EmailVerifyService.java
> +public class EmailVerifyService {
[ca585f6](https://github.com/Q-int/Qint_backend/pull/3/commits/ca585f676bb792eed05d3a9c8de0e6252816b19d)

2024-08-24 04:03 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/err/exception/ErrorCode.java
> +    EMAIL_VERIFICATION_NOT_FOUND(404, "email_verification not found"),
[6779e74](https://github.com/Q-int/Qint_backend/pull/3/commits/6779e7498df197d9a840a84d5ed35038f82fff64)

2024-08-24 04:08 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/err/exception/ErrorCode.java
> +    EMAIL_NOT_VERIFIED(412, "email not verified"),
[d741feb](https://github.com/Q-int/Qint_backend/pull/3/commits/d741feb1abdddc92cf4f5d9895e0fc392d1b4cf8)

2024-08-24 05:55 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/security/jwt/JwtProperties.java
> +    private String header;
[69330c8](https://github.com/Q-int/Qint_backend/pull/3/commits/69330c8ee67a6713455446c115460059fd707f7f)
[90b95ea](https://github.com/Q-int/Qint_backend/pull/3/commits/90b95ea4ae9115473a9d1698f1b48e8ca0fbc67f)

2024-08-24 06:27 UTC, in-jun commented on src/main/java/org/example/qint_backend/domain/auth/service/LoginService.java
> +        return jwtTokenProvider.generateToken(user.getEmail(), "USER");
[f5baa73](https://github.com/Q-int/Qint_backend/pull/3/commits/f5baa73aeaff1e64a58144b932c3c65cd8595356)
[0c08244](https://github.com/Q-int/Qint_backend/pull/3/commits/0c082445de9c6921566d8b2356609b6861447166)

2024-08-24 09:55 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/global/err/exception/ErrorCode.java
> +    EMAIL_VERIFICATION_NOT_FOUND(401, "email doesn't verified"),
EMAIL_NOT_VERIFIED랑 통합해도 될 것 같습니다

2024-08-24 10:05 UTC, in-jun commented on src/main/java/org/example/qint_backend/global/err/exception/ErrorCode.java
> +    EMAIL_VERIFICATION_NOT_FOUND(401, "email doesn't verified"),
[b38f058](https://github.com/Q-int/Qint_backend/pull/3/commits/b38f058460f6acd640dcf7e9fba46ecaad2ba920)
[5292ba4](https://github.com/Q-int/Qint_backend/pull/3/commits/5292ba43d3b0e1af9f00f11beef5082aaa53c56f)
[9340334](https://github.com/Q-int/Qint_backend/pull/3/commits/93403346e465a2cb85feb67604f83a6de321af12)

2024-08-24 10:10 UTC, Daybreak312 approved these changes
좋습니다!
전체적으로 코드가 깔끔하네요.

2024-08-24 10:16 UTC, merged