feat: Answer, Question 엔티티 추가
Q-int/Qint_backend pull request #4
Opened 2024-08-09 14:27 UTC by 1210thatman

- question 도메인 엔티티 생성
 - Question 엔티티 생성
 - Answer 엔티티 생성
 - UserIncorectAnser 엔티티 생성

 - 연관 관계 매핑

- 변경사항
 - Category를 엔티티가 아닌 Enum 클래스로 변경
 - properties 를 yml로 변경

2024-08-10 12:27 UTC, HyunSu1768 commented on src/main/java/org/example/qint_backend/domain/question/domain/Question.java
위에서 Category 클래스가 구현되어 있는데, Question 클래스에서 사용해야 하는데 까먹으신것 같아요 !

2024-08-10 12:33 UTC, HyunSu1768 commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
User 의 틀린 문제를 담아두고 있는 클래스인 것 같은데, 어떤 유저인지 확인할 수 있는 필드가 없는것 같습니다.

하나의 궁금한 점이 있는데, Answer 에 userID를 넣은 뒤, isCorrect 로 틀렸는지 맞았는지 확인할 수 있도록 하는 클래스를 만들지 않고, 따로 UserIncorrectAnswers 를 만드신 이유는 무엇일까요?

2024-08-10 12:34 UTC, HyunSu1768 commented on src/main/java/org/example/qint_backend/domain/question/domain/Answer.java
> +    private Question question;
text @Column 속성중 length 속성으로 text의 최대 길이를 설정하는게 좋을것 같아요 🙂

2024-08-10 12:56 UTC, Daybreak312 requested changes

2024-08-10 12:56 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/domain/Answer.java
> +    private Question question;
@JoinColumn도 @Column과 동일하게 컬럼 속성 지정 가능하니 nullable 설정해주세요

2024-08-10 12:56 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/domain/Answer.java
전체적으로 코드 스타일(띄어쓰기 위치 ex - updatable=false, nullable = false 등, 줄바꿈 위치) 등이 일치하지 않습니다.
윈도우 기준 Ctrl + Alt + L 누르면 자동으로 인텔리제이 기본 스타일로 맞춰주니 모두 이용하시면 될 것 같습니다.

2024-08-10 12:56 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/domain/Answer.java
updatable(수정 가능 여부)도 명시해주면 좋을 것 같습니다.

2024-08-10 12:56 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/domain/Question.java
> +@NoArgsConstructor
기본 생성자의 경우, JPA 표준에서 요구하는 기능이지 저희가 사용하는 기능은 아니기에 @NoArgsConstructor(accss = AccessLevel.PROTECTED)로 부착하여 접근 제어자를 protected로 돌려주시는 게 좋습니다.

2024-08-10 13:58 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
Answer의 isCorrect는 각 선지 중 어떤 선지가 정답인지를 클라이언트에 제공하는 역할로 활용됩니다. 

UserIncorrectAnswers를 따로 만든 이유는 나중에 user가 오답을 확인 할때, 틀렸던 문제에 대한 정보(정답, 오답, 해설)를 확인할 수 있도록 하기 위해서 입니다.

여기에서 더 수정할 부분이 있으면 말씀해주세요.

2024-08-11 06:27 UTC, HyunSu1768 commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
그러면, 추후에 유저가 맞춘 문제에 대해서 확인할 때 UserCorrectAnswers 를 새롭게 만들어야 할 것 같은데
UserAnswers 라는 클래스를 만들어서 Question 에 대해서 틀렸던 문제, 맞았던 문제에 대한 정보를 저장해 중복되는 데이터를 없앨 수 있을것 같은데 어떻게 생각하세요??

2024-08-11 07:09 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/Question.java
c116aa53f563ef541574c522ca58cd0b0099a207

2024-08-11 11:52 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
기본적으로 제출되는 문제 수가 15개로 동일하기 때문에, 정오답률 계산 시에는 user의 오답 수 만 있으면 되고
 user는 user의 오답에 대해서만 해설, 정답등의 데이터를 제공 받기 때문에 UserInCorrectAnswers만 만들었던 것 같습니다.
 이런 로직에서도 UserCorrectAnswers가 필요할까요?

2024-08-11 11:52 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
기본적으로 제출되는 문제 수가 15개로 동일하기 때문에, 정오답률 계산 시에는 user의 오답 수 만 있으면 되고
 user는 user의 오답에 대해서만 해설, 정답등의 데이터를 제공 받기 때문에 UserInCorrectAnswers만 만들었던 것 같습니다.
 이런 로직에서도 UserCorrectAnswers가 필요할까요?

2024-08-11 11:53 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
중복 문제나 채점은 클라이언트 쪽에서 일단은 담당하기로 했습니다

2024-08-12 03:43 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/Answer.java
ac5e618dff90a7fdcf7629bf68e3f21a01e2f71c

2024-08-12 03:51 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/Question.java
> +@NoArgsConstructor
49d6c582f165f2e8805e1e6881aa0d7be56c612d

2024-08-13 03:00 UTC, HyunSu1768 approved these changes

2024-08-13 05:23 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
> +    private Answer answer;
nullable은 기본값이 true입니다.
false로 명시해주세요.

2024-08-13 05:23 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
> +    @OneToOne
연관관계가 잘못 맺어졌네요.
OneToOne으로 선언하면 Answer 테이블의 row 하나당 UserIncorrectAnswers row 하나만 연관관계를 맺을 수 있게 됩니다.
Answer 1 : N UserIncorrectAnswers가 맞습니다.

2024-08-13 07:49 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
> +    private Answer answer;
7e62fb45c39220821405bdbc9762a64224ffc790

2024-08-13 07:55 UTC, 1210thatman commented on src/main/java/org/example/qint_backend/domain/question/domain/UserIncorrectAnswers.java
> +    @OneToOne
1e93bb5b42de7c3c1a9deb448b23ba03595da428

2024-08-13 07:56 UTC, Daybreak312 approved these changes
좋습니다 ! 🍰

2024-08-20 08:15 UTC, coehgns reviewed
좋은 것 같습니다.

2024-08-20 08:18 UTC, in-jun approved these changes
감사합니다.

2024-08-20 08:39 UTC, merged