merge: 유저 관련 API 작성
Q-int/Qint_backend pull request #7
Opened 2024-08-24 17:45 UTC by coehgns

2024-08-25 12:43 UTC, Daybreak312 requested changes
전체적으로 나쁘지 않습니다.
코멘트 남긴 부분만 수정해주세요

2024-08-25 12:43 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/domain/repository/AnswerRepository.java
> +    Optional<Answer> findAllByQuestionAndAndIsCorrectIsTrue(Question question);
중간에 AndAnd가 있네요 수정해주세요

2024-08-25 12:43 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/facade/AnswerFacade.java
> +    public Answer getAllByQuestionAndAndIsCorrectIsTrue(Question question) {
중간에 AndAnd 수정해주세요

2024-08-25 12:43 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/user/service/IncorrectProblemsService.java
> +public class IncorrectProblemsService {
다른 Service 네이밍들이 다 동사형으로 작성되었기 때문에, 맞추어서 GetIncorrectProblemsService 정도로 리네이밍 하는 게 적절해 보입니다.

2024-08-25 12:43 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/user/service/MyPageService.java
> +public class MyPageService {
다른 Service 네이밍들이 다 동사형으로 작성되었기 때문에, 맞추어서 GetMyPageService 정도로 리네이밍 하는 게 적절해 보입니다.

2024-08-25 12:43 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/user/presentation/UserController.java
> +    public List<UserIncorrectAnswerResponse> selectIncorrectAnswers() {
반환값이 컬렉션이면 클라이언트가 파싱하기 어렵습니다.
DTO로 한 번 감싸주세요

2024-08-26 03:05 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/user/service/IncorrectProblemsService.java
> +public class IncorrectProblemsService {
df1e7ddf034397375e1b498bb9ad99a0d6a16a8c

2024-08-26 03:05 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/user/service/MyPageService.java
> +public class MyPageService {
24c1a2e59a4fd80765f27f0dcc2f90d6e583155d

2024-08-26 03:06 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/domain/repository/AnswerRepository.java
> +    Optional<Answer> findAllByQuestionAndAndIsCorrectIsTrue(Question question);
8da1a7a4d8a30803858a449af335e2cb59033f08

2024-08-26 03:07 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/facade/AnswerFacade.java
> +    public Answer getAllByQuestionAndAndIsCorrectIsTrue(Question question) {
8aa4f49aa8bd5e17fe3fb0ef3564aa129d23a579

2024-08-26 12:52 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/user/presentation/UserController.java
> +    public List<UserIncorrectAnswerResponse> selectIncorrectAnswers() {
93d3050e1112b053713f0d2519082c53575f3887

2024-08-26 13:02 UTC, Daybreak312 approved these changes
좋습니다!

2024-08-26 13:04 UTC, in-jun approved these changes

2024-08-26 13:05 UTC, merged