merge: 문제 출제 API 작성
Q-int/Qint_backend pull request #8
Opened 2024-09-08 13:59 UTC by coehgns

2024-09-10 13:32 UTC, Daybreak312 requested changes
멘토링 겸 길고 자세히 코멘트 남겨두었습니다.

천천히 읽어보시고 충분히 생각해보신 뒤에 코드에 반영해주세요.
이번에도 마찬가지로 이해 안되시면 연락주세요.

2024-09-10 13:32 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/request/CategoryRequest.java
> +    List<String> categorys;
category의 복수형은 categories 입니다.

2024-09-10 13:32 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryElement.java
> +    private Long question_id;
카멜 케이스로 작성해주세요.

2024-09-10 13:32 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                .build();
Builder 패턴의 오남용으로 인해 들여쓰기 깊이가 너무 깊어 가시성과 판독성이 다소 떨어집니다.

생성 인자가 2개, 3개 정도, 특히 1개일 경우에는 생성자 혹은 팩토리 메소드 _(`Category.valueOf(String)`과 같이 인스턴스 생성이 목적인, 마치 공장과 같은 메소드)_ 를 사용하는 편이 좋습니다.

이 경우처럼 가독성을 위해 디자인 패턴을 사용했음에도 되려 난독화되는 경우엔 우선적으로 디자인 패턴을 제거해보고, 다양한 방식으로 표현해보고 비교하면 더욱 양질의 코드를 작성할 수 있게 될겁니다.

디자인 패턴은 보다 좋은 코드를 위한 도구일 뿐이니 목 매일 필요는 없습니다.

코드를 작성할 땐 이전에 계속 해오던 방식과는 다른, 여러 방법을 시도해보며 연습하면 좋습니다.
개발자로서의 사고 수준을 고취하는데에 많은 도움이 됩니다.

2024-09-10 13:32 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +        incorrectQuestions.addAll(allQuestions);
이전에 틀린 문제를 저장한다는 목적이 분명한 incorrectQuestions를 그대로 사용하기 보다,
새로운 리스트 객체에 각각 더해 저장하는 편이 알고리즘 이해하는 데 편할 것 같습니다.

2024-09-10 13:32 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +        Collections.shuffle(incorrectQuestions);
따로 섞은 뒤에 합친 후 다시 한 번 더 섞는, 비효율적인 로직으로 보입니다.
합치고 -> 섞은 뒤에 -> limit으로 자르는 편이 좋아보입니다.

2024-09-10 13:32 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                .collect(Collectors.toList());
이전에 선재한테 들었을 땐 문제 출제 시 이전에 틀린 문제가 모두 포함되어 출제되게 한 것으로 들었는데, 혹시 다르게 알고 있는 게 아닌지 확인해주세요.

2024-09-10 13:32 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +        allQuestions.removeAll(incorrectQuestions);
한 트랜잭션 _(`@Transactional`)_ 으로 묶여있지 않아서, 37번 줄의 `userIncorrectAnswersRepository.findAllByQuestionCategory(Category.valueOf(category))`에서 추출해낸 Question Entity와 42번 줄의 `questionRepository.findAllByCategory(Category.valueOf(category))`에서 조회한 Question Entity가 id는 같더라도 동일한 Java Object임이 보장되지 않습니다.

또한, for문 안에서는 `allQuestions`가 카테고리에 해당하는 모든 문제들을 담지만 블록 바깥에서 `incorrecQuestions`를 제거하는 모습에서, `allQuestions`는 이전에 틀린 문제를 제외한 나머지 문제들을 담는 컬렉션임이 바로 와닿지 않았습니다.

변수 이름 수정과, for문 내부에서 if문을 통해 한 번 틀린 문제는 추가하지 않도록 하여 보다 명확히 하면 읽기 쉬울 것 같습니다.

이미 시간 복잡도는 충분히 높고, 수정하려하면 되려 복잡해지니 아직은 신경쓰지 않으셔도 될 것 같습니다.

2024-09-10 13:32 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +            allQuestions.addAll(questionRepository.findAllByCategory(Category.valueOf(category)));
Category.valueOf()도 배열 순회 연산이라, 위처럼 반복하면 비용이 꽤 있습니다. 변수로 저장하고 사용해주세요.

2024-09-11 08:15 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +        Collections.shuffle(incorrectQuestions);
저희가 이전에 틀린 문제들을 우선적으로 출제해야 해서 출제 할 List에 이전에 틀린 문제(incorrectQuestions)와 그 외 문제(이전에 틀린 문제)들(allQuestions) 순서로 넣고 List 앞에서 부터 출제할 문제들의 개수를 잘라야 할 것 같습니다. 섞은 뒤에 limit을 하면 이전에 틀린 문제를 우선적으로 출제를 못할 것 같습니다. 
그래서 합치고 -> limit -> 섞는 방법으로 하려고 합니다.
다른 방법이 있으시면 알려주시면 감사하겠습니다.

2024-09-11 08:17 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                .collect(Collectors.toList());
출제 할 List에 이전에 틀린 문제들(incorrectQuestoins)을 우선적으로 출제 하기 위해서 이전에 틀린 문제들(incorrectQuestoins)을 먼저 넣고 그 뒤에 그 외 문제들(allQuestions)을 넣어서 limit으로 문제의 개수 만큼 자른 후 섞으려고 합니다.

2024-09-14 06:02 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/request/CategoryRequest.java
> +    List<String> categorys;
83a1ce5024d67e9d966e05a5679ca3ccd5a70e72

2024-09-14 06:02 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryElement.java
> +    private Long question_id;
52b92d3fcd62c042f9556ba98c7c9c9ffa9ce905

2024-09-14 06:02 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +            allQuestions.addAll(questionRepository.findAllByCategory(Category.valueOf(category)));
14e58e926f14633a9ac159011544707a6d922d26

2024-09-14 06:03 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +        incorrectQuestions.addAll(allQuestions);
a58651d09069f80fff0c2d3cce86e75b28ed1760

2024-09-14 06:03 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +        allQuestions.removeAll(incorrectQuestions);
2da0378d6171180a5052afc5084e5aff95f6adaf
1e99f2cbcb7f5a04b753a794abdd58866a90aa1d

2024-09-14 06:04 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                .build();
901f36e63c32d1ce9ad5b593596e856629dcd68d

2024-09-16 15:27 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +        Collections.shuffle(incorrectQuestions);
제안하신 방식대로 진행하면 될 것 같습니다 👍

2024-09-16 15:58 UTC, Daybreak312 requested changes
미안해용 좀 늦게 봤습니다.. 😥

전체적으로 나쁘지 않습니다.
JPA, 특히 Transactional 관련해서 좀 더 찾아보시면 좋을 것 같아요.

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/QuestionController.java
> +public class QuestionController {
요청 경로( "/problems" )와 도메인 명명( "Question" )이 다른데, 웬만해서는 통일 하시는 편이 좋습니다.
요청 경로 또한 프로덕트 관점에서 도메인에 대한 명명이기 때문에, 다르게 할 이유가 없습니다.

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/request/CategoryRequest.java
> +    List<String> categories;
접근 제어자 명시해주세요.

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                            .map(answer -> new OptionsElement(answer.getId(), answer.getText()))
지금처럼 생성자 인자로 한 개의 객체만 사용되는 경우엔 static 팩토리 메소드를 사용해서 `Options.of(answer)`형태로 호출하도록 리팩토링하면 더 좋을 것 같아요.

`public static Options of(Answer answer);`

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                .collect(Collectors.toList());
Stream API( `Collection API`에서 `stream()` 메소드를 통해 호출 ) 안에 자체적으로 `toList()` 메소드가 내장되어 있습니다.
`List.stream().map(...).toList();` 형태로 호출 가능합니다.

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryResponse.java
> +@Builder
이제 빌더를 사용하지 않으니 제거해주세요.

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryElement.java
> +@Builder
이제 빌더를 사용하지 않으니 제거해주세요.

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/OptionsElement.java
> +@Builder
이제 빌더를 사용하지 않으니 제거해주세요.

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryElement.java
> +public class QuestionByCategoryElement {
굳이 다른 QuestionElement 들과 분리할 필요는 없어보입니다.

API 응답 내용과 클라이언트 요구 내용 간의 관계를 페칭(Fetching)이라고 하는데,
클라이언트의 요구보다 더 많이 주는 걸 오버 페칭, 적게 주는 걸 언더 페칭이라 부릅니다.

현재의 경우는 이미 클라이언트가 카테고리 내용을 알고 있고, 딱히 중요하지도 않기에 적절히 페칭이 이루어져 보이긴 합니다만
이렇게 분리해버리면 차후 확장성을 고려했을 때 재사용성이 낮아 되려 DX(Developer Experience, 개발자 경험 - UX와 유사)를 해칠 수도 있을 것 같습니다.
조금 오버 페칭이긴 하더라도 Category도 포함해 재사용성을 증진하는 편이 나아보입니다.

다만 제 의견일 뿐이기에 딱히 안그럴 것 같다 싶으시면 무시하셔도 됩니다.

2024-09-16 15:58 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +    @Transactional
테이블의 행을 수정하거나 하는 동작 없이, 단순 읽기 작업만 있기에 `readOnly` 옵션을 `true`로 주는 게 좋습니다.

명시적으로 해당 트랜잭션은 읽기 작업만 수행한다고 알릴 수 있고,
내부적으로 쓰기 작업에 대한 선행 작업 및 후행 작업을 진행하지 않아 성능적으로도 이점을 가집니다.

2024-09-18 13:45 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/presentation/QuestionController.java
> +public class QuestionController {
499f4b08d8e84c94f5527923f9891322093b8ff3

2024-09-18 13:46 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryResponse.java
> +@Builder
cc8665757c52c0b8367f8b4a60ff928b046b1e0c

2024-09-18 13:46 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryElement.java
> +@Builder
cc8665757c52c0b8367f8b4a60ff928b046b1e0c

2024-09-18 13:46 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/OptionsElement.java
> +@Builder
cc8665757c52c0b8367f8b4a60ff928b046b1e0c

2024-09-18 13:50 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/request/CategoryRequest.java
> +    List<String> categories;
4fa45d4a88f190c83513d05f379a47b1164093cf

2024-09-18 13:50 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +    @Transactional
0d5d8af3cabc534db8d036f2b8bbdb560f4aa40b

2024-09-18 13:51 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                            .map(answer -> new OptionsElement(answer.getId(), answer.getText()))
435cfc2e439491b174f668b92fb4732a2bf128b0

2024-09-18 13:54 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                .collect(Collectors.toList());
afd4a9d5d0a5c9ca639fcddc8d3d6055f6f887ea

2024-09-18 14:25 UTC, Daybreak312 reviewed
간단한 코멘트만 남긴 마지막 리뷰입니다.
남긴 코멘트들만 반영해주세요.

2024-09-18 14:25 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                            .collect(Collectors.toList());
`.collect(Collectors.toList())` 전부 `toList()`로 수정해주세요

2024-09-18 14:25 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryElement.java
> +    }
`@AllArgsConstructor`로 대체해도 될 것 같아요
다른 VO들에도 적용해주세요

2024-09-18 14:25 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +        }
추후에 Map으로 관리해서 시간 복잡도 개선할 수 있어보이네요. 차후 리팩토링할 때 고민해보시면 좋을 것 같습니다.

2024-09-18 14:35 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/presentation/dto/response/QuestionByCategoryElement.java
> +    }
d90d4bcb16f20cf9cdb651edf5b779501d600fbd

2024-09-18 14:35 UTC, coehgns commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                            .collect(Collectors.toList());
638f2964fefa8c5faf841e9d3dbc23548908f858
5e0a09d9cfaac58256cf0b948fa800888471ba78

2024-09-18 14:37 UTC, Daybreak312 commented on src/main/java/org/example/qint_backend/domain/question/service/GetQuestionByCategoryService.java
> +                .collect(Collectors.toList());
`toList()` 하나 남았어요

2024-09-19 10:50 UTC, Daybreak312 approved these changes
좋아용 👍

2024-09-19 10:54 UTC, merged